/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ProjetoPP_Fase1.LogicClasses.Server;

import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author -nikeiZprooo-
 */
public class ServerAPP extends javax.swing.JFrame implements IServerUI{
    private ServerImplementation server;
    private SimpleDateFormat dateFormat;
    
    /**
     * Creates new form ServerAPP
     */
    public ServerAPP() {
        initComponents();
        
        System.runFinalizersOnExit(true);
        
        dateFormat = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss - ");
        
        try {
            sendMessage("A criar ligações à base de dados...");
            this.server = new ServerImplementation(this);
            sendMessage("Ligações criadas!");
            sendMessage("A criar o servidor de RMI...");
            Registry reg = LocateRegistry.createRegistry(1099);
            reg.rebind("server", server);
            sendMessage("Servidor pronto!!!");
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao criar o servidor de RMI... a fechar...");
            System.exit(0);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao criar as ligações à base de dados... a fechar...");
            System.exit(0);
        } catch (NoSuchAlgorithmException ex) {
            // Erro que nunca acontece...
            JOptionPane.showMessageDialog(this, "Erro... A sair");
            System.exit(0);
        }
    }
    
    @Override
    public synchronized void sendMessage(String msg) {
        consolaTextArea.append(dateFormat.format(System.currentTimeMillis()) + msg + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        consolaTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto PP - Server");
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        consolaTextArea.setEditable(false);
        consolaTextArea.setColumns(20);
        consolaTextArea.setRows(5);
        consolaTextArea.setPreferredSize(new java.awt.Dimension(200, 300));
        jScrollPane1.setViewportView(consolaTextArea);

        getContentPane().add(jScrollPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerAPP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea consolaTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
