/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ProjetoPP_Fase1.LogicClasses.ClientRegister.ClientPanels;

import DataClasses.OfertaRecursos;
import ProjetoPP_Fase1.LogicClasses.ClientRegister.ClientAPP;
import ProjetoPP_Fase1.LogicClasses.ClientRegister.ClientRegisterImplementation;
import ProjetoPP_Fase1.LogicClasses.ClientRegister.Exceptions.AreaAtuacaoNotValidException;
import ProjetoPP_Fase1.LogicClasses.ClientRegister.Exceptions.DetalhesOfertaNotValidException;
import ProjetoPP_Fase1.LogicClasses.ClientRegister.Exceptions.NumeroCandidatosNotValidException;
import ProjetoPP_Fase1.LogicClasses.ClientRegister.Exceptions.PerfilCandidatosNotValidException;
import ProjetoPP_Fase1.LogicClasses.ClientRegister.Exceptions.TituloNotValidException;
import ProjetoPP_Fase1.LogicClasses.DBConnection.Exceptions.KeyNotReturnedException;
import java.io.File;
import java.io.IOException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author -nikeiZprooo-
 */
public class AdicionarOfertaEmpregoPanel extends javax.swing.JPanel {
    private final ClientAPP clientUI;
    private final ClientRegisterImplementation client;
    
    private ArrayList<AdicionarAnexoPanel> listaAnexos;
    
    /**
     * Creates new form AdicionarOfertaEmpregoPanel
     */
    public AdicionarOfertaEmpregoPanel(ClientRegisterImplementation client, ClientAPP clientUI) {
        initComponents();
        anexosScrollPanel.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        this.client = client;
        this.clientUI = clientUI;
        this.listaAnexos = new ArrayList<>();
        adicionarAnexoField();
    }
    
    private void adicionarAnexoField(){
        AdicionarAnexoPanel newAnexoPanel = new AdicionarAnexoPanel();
        anexosPanel.add(newAnexoPanel);
        listaAnexos.add(newAnexoPanel);
        clientUI.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        detalhesOfertaTextField = new javax.swing.JTextField();
        tituloTextField = new javax.swing.JTextField();
        perfilCandidatosTextField = new javax.swing.JTextField();
        submeterButao = new javax.swing.JButton();
        cancelarButao = new javax.swing.JButton();
        adicionarOutroAnexoButton = new javax.swing.JButton();
        anexosScrollPanel = new javax.swing.JScrollPane();
        anexosPanel = new javax.swing.JPanel();
        numeroCandidatosNecessariosTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        areaAtuacaoComboBox = new javax.swing.JComboBox();

        jLabel1.setText("Titulo:");

        jLabel2.setText("Detalhes da Oferta:");

        jLabel3.setText("Número de Candidatos Necessários:");

        jLabel4.setText("Perfil dos Candidatos:");

        submeterButao.setText("Submeter");
        submeterButao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submeterButaoActionPerformed(evt);
            }
        });

        cancelarButao.setText("Cancelar");
        cancelarButao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButaoActionPerformed(evt);
            }
        });

        adicionarOutroAnexoButton.setText("Adicionar outro anexo");
        adicionarOutroAnexoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarOutroAnexoButtonActionPerformed(evt);
            }
        });

        anexosPanel.setLayout(new javax.swing.BoxLayout(anexosPanel, javax.swing.BoxLayout.Y_AXIS));
        anexosScrollPanel.setViewportView(anexosPanel);

        jLabel6.setText("Área da Oferta:");

        areaAtuacaoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rede", "Desenvolvimento", "Bases de Dados" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anexosScrollPanel)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detalhesOfertaTextField)
                            .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(adicionarOutroAnexoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submeterButao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarButao))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(areaAtuacaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(perfilCandidatosTextField)
                            .addComponent(numeroCandidatosNecessariosTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(detalhesOfertaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numeroCandidatosNecessariosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(perfilCandidatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(areaAtuacaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anexosScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButao)
                    .addComponent(submeterButao)
                    .addComponent(adicionarOutroAnexoButton))
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submeterButaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submeterButaoActionPerformed
        ArrayList<File> files = new ArrayList<>();
        for (AdicionarAnexoPanel panel : listaAnexos){
            if(panel.getAnexo() != null)
                files.add(panel.getAnexo());
        }
        
        OfertaRecursos.AREA_ATUACAO areaAtuacao = null;
        switch(areaAtuacaoComboBox.getSelectedIndex()){
            case 0:
                areaAtuacao = OfertaRecursos.AREA_ATUACAO.REDE;
                break;
            case 1:
                areaAtuacao = OfertaRecursos.AREA_ATUACAO.DESENVOLVIMENTO;
                break;
            case 2:
                areaAtuacao = OfertaRecursos.AREA_ATUACAO.BASES_DADOS;
                break;
        }
        
        try {
            int nrCandidatos = Integer.parseInt(numeroCandidatosNecessariosTextField.getText());
            client.novaOfertaEmprego(tituloTextField.getText(), detalhesOfertaTextField.getText(), nrCandidatos, perfilCandidatosTextField.getText(), files, areaAtuacao);
            JOptionPane.showMessageDialog(this, "A oferta foi adicionada com sucesso!");
            clientUI.comeHere(this);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "O campo \"Número de Candidatos Necessários\" tem que ser preenchido com um número.");
        } catch (TituloNotValidException ex) {
            JOptionPane.showMessageDialog(this, "O campo \"Titulo\" tem que estar preenchido.");
        } catch (DetalhesOfertaNotValidException ex) {
            JOptionPane.showMessageDialog(this, "O campo \"Detalhes da Oferta\" tem que estar preenchido.");
        } catch (NumeroCandidatosNotValidException ex) {
            JOptionPane.showMessageDialog(this, "O campo \"Número de Candidatos Necessários\" tem que ser um número maior que 0.");
        } catch (PerfilCandidatosNotValidException ex) {
            JOptionPane.showMessageDialog(this, "O campo \"Perfil dos Candidatos\" tem que estar preenchido.");
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Erro de RMI. Tente novamente.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro de SQL. Tente novamente.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro no sistema de ficheiros. Um dos anexos não é válido.");
        } catch (KeyNotReturnedException ex) {
            JOptionPane.showMessageDialog(this, "Erro de SQL. A Oferta foi adicionada mas os anexos não.\nPor favor, tente outra vez.\nSe o erro persistir contacte um administrador.");
        } catch (AreaAtuacaoNotValidException ex) {
            JOptionPane.showMessageDialog(this, "O campo \"Area de Atuação\" é inválido.");
        }
    }//GEN-LAST:event_submeterButaoActionPerformed

    private void cancelarButaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButaoActionPerformed
        clientUI.comeHere(this);
    }//GEN-LAST:event_cancelarButaoActionPerformed

    private void adicionarOutroAnexoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarOutroAnexoButtonActionPerformed
        adicionarAnexoField();
    }//GEN-LAST:event_adicionarOutroAnexoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarOutroAnexoButton;
    private javax.swing.JPanel anexosPanel;
    private javax.swing.JScrollPane anexosScrollPanel;
    private javax.swing.JComboBox areaAtuacaoComboBox;
    private javax.swing.JButton cancelarButao;
    private javax.swing.JTextField detalhesOfertaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField numeroCandidatosNecessariosTextField;
    private javax.swing.JTextField perfilCandidatosTextField;
    private javax.swing.JButton submeterButao;
    private javax.swing.JTextField tituloTextField;
    // End of variables declaration//GEN-END:variables
}
