package LogicClasses.ClientRegister.ClientPanels;

import DataClasses.OfertaRecursos;
import LogicClasses.ClientRegister.ClientAPP;
import LogicClasses.ClientRegister.ClientRegisterImplementation;
import LogicClasses.ClientRegister.Exceptions.AreaAtuacaoNotValidException;
import LogicClasses.ClientRegister.Exceptions.ContactNotValidException;
import LogicClasses.ClientRegister.Exceptions.NameNotValidException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * Painel que permite adicionar Ofertas de Recursos
 */
public class AdicionarOfertaRecursosPanel extends javax.swing.JPanel {
    private ClientRegisterImplementation client;
    private ClientAPP clientUI;
    
    /**
     * Creates new form adicionarOfertaRecursosPanel
     */
    public AdicionarOfertaRecursosPanel(ClientRegisterImplementation client, ClientAPP clientUI) {
        initComponents();
        this.client = client;
        this.clientUI = clientUI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        areaAtuacaoComboBox = new javax.swing.JComboBox();
        contactoTextField = new javax.swing.JTextField();
        nomeTextField = new javax.swing.JTextField();
        cancelarButao = new javax.swing.JButton();
        submeterButao = new javax.swing.JButton();

        jLabel4.setText("Nome:");

        jLabel5.setText("Contacto:");

        jLabel6.setText("Area de Atuação:");

        areaAtuacaoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rede", "Desenvolvimento", "Bases de Dados" }));

        cancelarButao.setText("Cancelar");
        cancelarButao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButaoActionPerformed(evt);
            }
        });

        submeterButao.setText("Submeter");
        submeterButao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submeterButaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(68, 68, 68)
                                .addComponent(nomeTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(areaAtuacaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 339, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(52, 52, 52)
                                .addComponent(contactoTextField))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submeterButao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarButao)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5))
                    .addComponent(contactoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addComponent(areaAtuacaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButao)
                    .addComponent(submeterButao))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submeterButaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submeterButaoActionPerformed
        OfertaRecursos.AREA_ATUACAO areaAtuacao = null;
        switch(areaAtuacaoComboBox.getSelectedIndex()){
            case 0:
                areaAtuacao = OfertaRecursos.AREA_ATUACAO.REDE;
                break;
            case 1:
                areaAtuacao = OfertaRecursos.AREA_ATUACAO.DESENVOLVIMENTO;
                break;
            case 2:
                areaAtuacao = OfertaRecursos.AREA_ATUACAO.BASES_DADOS;
                break;
        }
        
        try {
            client.novaOfertaRecursos(nomeTextField.getText(),contactoTextField.getText(), areaAtuacao);
            JOptionPane.showMessageDialog(this, "A oferta foi adicionada com sucesso!");
            clientUI.comeHere(this);
        } catch (NameNotValidException ex) {
            JOptionPane.showMessageDialog(this, "O campo \"Nome\" tem de estar preenchido.");
        } catch (ContactNotValidException ex) {
            JOptionPane.showMessageDialog(this, "O campo \"Contacto\" tem de estar preenchido.");
        } catch (AreaAtuacaoNotValidException ex) {
            JOptionPane.showMessageDialog(this, "O campo \"Area de Atuação\" é inválido.");
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Erro de RMI. Tente novamente.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro de SQL. Tente novamente.");
        } 
    }//GEN-LAST:event_submeterButaoActionPerformed

    private void cancelarButaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButaoActionPerformed
        clientUI.comeHere(this);
    }//GEN-LAST:event_cancelarButaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox areaAtuacaoComboBox;
    private javax.swing.JButton cancelarButao;
    private javax.swing.JTextField contactoTextField;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JButton submeterButao;
    // End of variables declaration//GEN-END:variables
}
